<?php

namespace FraisBundle\Repository;

/**
 * FicheFraisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheFraisRepository extends \Doctrine\ORM\EntityRepository
{
  public function getFraisByDate($user)
  {
    $userId = $user->getId();
    $request = $this->createQueryBuilder('ff')
                    ->where('ff.user ='. $userId )
                    ->orderBy('ff.created', 'DESC')
                    ->getQuery()
                    ->execute()
    ;
    return $request;
  }

  public function getLastEntity($user) {
    return $this
      ->createQueryBuilder('e')
      ->orderBy('e.date', 'DESC')
        ->where('e.user ='. $user)
        ->setMaxResults(1)
        ->getQuery()
        ->getResult()
    ;
  }
}
