services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#        
    user.connexion:
        class: UserBundle\EventListener\ConnexionListenner
        arguments: ['@router', '@security.token_storage', '@doctrine']
        tags:
            - { name: kernel.event_subscriber }
